### ISSUE TITLE
Message delivering

### ISSUE THREAD

**Issue by andius** [eddroid/github-skype#1]
I have some troubles with using skypekit and github-skype. When i push commit to my github repository, my skypekit process gives the following:

``` bash
[LIBSKYPEKIT /home/andius/dev/libskypekit/src/SkypekitQueue.cpp:133] SkypekitQueue::clear mutex unlocking
[LIBSKYPEKIT /home/andius/dev/libskypekit/src/SkypekitQueue.cpp:135] SkypekitQueue::clear mutex unlocked
[LIBSKYPEKIT /home/andius/dev/libskypekit/src/SkypekitQueue.cpp:26] Delete mutex object 0x9f87250
I, [2012-09-18T11:13:02.534645 #28322]  INFO -- : initializing...
initialized.
starting ...
started
logging in
0
logged in
#<Skypekit::FFI::AccountStatusData:0x9dbe79c> status=connecting_to_p2p skypename=test_application_bot reason=0
#<Skypekit::FFI::AccountStatusData:0x9dbe594> status=connecting_to_server skypename=test_application_bot reason=0
#<Skypekit::FFI::AccountStatusData:0x9dbe3dc> status=logging_in skypename=test_application_bot reason=0
#<Skypekit::FFI::AccountStatusData:0x9dbe210> status=initializing skypename=test_application_bot reason=0
Congrats! We are Logged in!
#<Skypekit::FFI::AccountStatusData:0x9dbe080> status=logged_in skypename=test_application_bot reason=0
sending message to #andius/$ea72211d15941d5c
"testcommit" by andius <a.migalnikov@gmail.com> [https://github.com/andius/testapp/commit/052ad936f78e963062ddfd681b6d89fc55774698]
0
Terminating...

108.171.174.178 - - [18/Sep/2012 11:13:02] "POST / HTTP/1.1" 200 - 13.7214
```

It's ok, but i get messages in my skype conversation with large delay (about hours). And not all messages will be delivered.

**Comment by eddroid** [comment]
Thank you @andius for being the first brave soul to actually test this.

I find that messages sent through Skypekit don't appear in my Skype client until about 30 seconds after the message has been sent and confirmed. So if you send a message and immediately terminate, the message doesn't really get sent. It only gets stored in a local Skype database. You have to remain connected to the network for a little while longer to really send the message.

I pushed some changes that force the send_skype_message process to wait about 50 seconds before terminating to allow the message time to "commit" or "propagate" or whatever is happening inside the Skype network.
